### ISSUE TITLE
Add chat?

### ISSUE THREAD

**Issue by niccokunzmann** [chiefgewickelt/aud_test#11]
Ein Chat würde es erlauben, dass die Teilnehmer einander helfen.
Vielleicht ist das auch nicht nötig.

**Comment by chiefgewickelt** [comment]
hier ein befürworter des potentiellen chats.
welcherlei möglichkeiten bieten sich denn hier?

**Comment by niccokunzmann** [comment]
Man kann einen Chat mit Log-In machen.
Ich würde aber eigendlich lieber die Teilnehmer fragen, was sie brauchen. Ich schließe das mal. Du kannst es ja wieder aufmachen.
