### ISSUE TITLE
Rechtevergabe

### ISSUE THREAD

**Issue by chiefgewickelt** [chiefgewickelt/aud_test#12]
Es sollten mehr als eine Person administrative Tätigkeiten ausführen können.
Wie ist dies Möglich?

**Comment by niccokunzmann** [comment]
Settings -> Contributors -> niccokunzmann
daneben sollte ein dropdown sein, in dem man die Adminrechte einstellen
kann.

**Comment by chiefgewickelt** [comment]
nope :(

**Comment by niccokunzmann** [comment]
Ich habe mal denGitHub Support gefragt.

**Comment by niccokunzmann** [comment]
Das geht nur in Organisationen.
https://help.github.com/articles/differences-between-user-and-organization-accounts/
