### ISSUE TITLE
[HTML/CSS] Add styling to the page

### ISSUE THREAD

**Issue by niccokunzmann** [chiefgewickelt/aud_test#18]
The page https://chiefgewickelt.github.io/aud_test/index.html has vary simple styling.
Please add some CSS to make it prettier! You can change the HTML if needed.

These can be re-worked:
- [x] Heading
- [x] Execution button?
- [x] Output
- [x] Explanation text
- [x] Footer

**Comment by hakabuk** [comment]
Happy to tackle this one, if it's up for grabs

**Comment by niccokunzmann** [comment]
Welcome, sure it is up to you! You can let us know of small improvements
asap through a pull request, if you like. Happy to merge it.

**Comment by niccokunzmann** [comment]
#23 looks great. I think, it addresses all the points in the issue. Thanks @hakabuk !

**Comment by hakabuk** [comment]
Happy to help! :)
