### ISSUE TITLE
Test-Cases vorgeben

### ISSUE THREAD

**Issue by niccokunzmann** [chiefgewickelt/aud_test#3]
Die Idee: Ein Programm hat eine Eingabe und eine Ausgabe.
Diese werden gestestet.
Diese Test-Cases werden dargestellt und können ausgeführt werden.

**Comment by niccokunzmann** [comment]
Man kann folgendes machen:
1. assert-statements laufen lassen
2. unittest verwenden
3. testen, was geprintet wird, je nach Eingabe

**Comment by chiefgewickelt** [comment]
für die kommende Abgabe wre tatsächlich interessant, die ausgabe zu testen, nämlich die indices, welche im quicksortAlg. vertauscht werden...
ansonsten eine möglichkeit die rückgabewerte von funktionen mit vorgegebener schnittstelle zu testen..

**Comment by niccokunzmann** [comment]
Kannst du Beispiele vorgeben?

**Comment by niccokunzmann** [comment]
das Interface, das zu testen wäre, ist also:

```
def qicksort(l):
    """Sort l using quicksort inplace and print the indices of the list elements that get swapped."""
    # ...
    print(index_left, index_right)
    # ...
    return None
```

**Comment by chiefgewickelt** [comment]
es gibt jetzt eine Beispiellösung, die die indices in der Form "i,j" ausgibt.
wie verwenden wir diese, ohne sie zu veröffentlichen ?

**Comment by niccokunzmann** [comment]
Du kannst sie mir per Mail schicken: http://niccokunzmann.github.io/impressum
